# .github/workflows/main.yml
name: Main
on: [ push ]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *

      - name: Upload to Google Drive with OAuth
        uses: logickoder/g-drive-upload@main
        with:
          authType: 'oauth'
          clientId: ${{ secrets.GOOGLE_CLIENT_ID }}
          clientSecret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refreshToken: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          filename: 'archive.zip'
          folderId: ${{ secrets.FOLDER_ID }}
          name: 'documentation.zip' # optional string
          overwrite: 'true' # optional boolean
