name: Upload MP4 to Lark Base

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL file MP4 cần tải'
        required: true

jobs:
  upload-job:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      ORIGIN: "https://trans-cosmos.larksuite.com"
      # --- Thay trực tiếp các giá trị này (đã hardcode theo yêu cầu) ---
      COOKIE: "passport_web_did=7670174375420628706; passport_trace_id=7670174375437405917; QXV0aHpDb250ZXh0=562ff534f2b64d41a4507d1b74c166df; first_landing_url=https://accounts.larksuite.com/accounts/page/login?app_id=1&no_trap=1&redirect_uri=https%253A%252F%252Fwww.larksuite.com%252Fmessenger; landing_url=https://accounts.larksuite.com/accounts/page/login?app_id=1&no_trap=1&redirect_uri=https%253A%252F%252Fwww.larksuite.com%252Fmessenger; _gcl_au=1.1.887165197.1785851638; s_v_web_id=verify_msepyf6m_MqaiQnVR_NMLX_44rh_9XgK_GtivRInAnfXS; _fuid=NzBiMTdkM2ItZWRlOS00MTNiLWIzNjktMGJkMTFhNDQ5OWRl; session=XN0YXJ0-516tf649-1d4d-41ab-991f-999hbrleaq0k-WVuZA; session_list=XN0YXJ0-516tf649-1d4d-41ab-991f-999hbrleaq0k-WVuZA; login_recently=1; i18n_locale=vi-VN; is_anonymous_session=; lang=vi; i18n_locale=vi; js_version=1; et=ed08d86f867e54cd0acdf3d1ab6ba80c; _csrf_token=d03e92533775588c3d17ac1f7e91a6e40ce86c55-1785851902; ccm_cdn_host=//lf-package-sg.larksuitecdn.com
